name: smart_potsy
description: "Smart Potsy - Smart Plant Monitoring App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  fl_chart: ^0.69.2
  mobile_scanner: ^5.1.1 # QR კოდის სკანერი
  firebase_core: ^3.0.0 # Firebase ბაზა
  firebase_messaging: ^15.0.0 # Push notifications
  image_picker: ^1.0.7 # პროფილის ფოტო

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
